const ecehod = {
  branch: "Electronics and Communication Engineering (ECE)",
  name: "Dr. SRINIVAS BACHU",
  position: "Professor & HOD",
  qualifications: "Ph.D",
  description:
    "Dr. Srinivas Bachu has extensive experience in academics and administration, leading the department with a vision for excellence.",
  email: "ecehod@gnits.ac.in",
  phone: "040-29565856 Extn. 425",
  academicIdentity: "/academic-identity-link",
  photo: "/images/chairman.jpg",
};

const eceprofessors = [
  {
    id: 1,
    name: "Dr. VALIKI VIJAYA BHASER",
    position: "Professor & Examinations I/C",
    qualifications: "Ph.D",
    email: "vijaya.bhaser@gnits.ac.in",
    phone: "040-29565856 Extn. 414",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 2,
    name: "Dr. KOTAGIRI SHASHIDHAR",
    position: "Professor",
    qualifications: "Ph.D",
    email: "shashidhar@gnits.ac.in",
    phone: "040-29565856 Extn. 427",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 3,
    name: "Dr. MAHESH MUDAVATH",
    position: "Professor",
    qualifications: "Ph.D",
    email: "mahesh.m@gnits.ac.in",
    phone: "040-29565856 Extn. 412",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 4,
    name: "Dr. KRISHNA MEKALA",
    position: "Professor",
    qualifications: "Ph.D",
    email: "krishna.mekala@gnits.ac.in",
    phone: "040-29565856 Extn. 427",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 5,
    name: "Mrs. MADIPALLI SUMALATHA",
    position: "Associate Professor",
    qualifications: "M.Tech",
    email: "sumalatha@gnits.ac.in",
    phone: "040-29565856 Extn. 425",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 6,
    name: "Mrs. SHIRISHA DUBBAKA",
    position: "Associate Professor",
    qualifications: "M.Tech",
    email: "shirisha.d@gnits.ac.in",
    phone: "040-29565856 Extn. 414",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 7,
    name: "Mrs. SOWJANYA REDDY MALLREDDY",
    position: "Associate Professor",
    qualifications: "M.Tech",
    email: "sowjanya.reddy@gnits.ac.in",
    phone: "040-29565856 Extn. 412",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 8,
    name: "Mrs. VIJAYAPURAM KEERTHI",
    position: "Associate Professor",
    qualifications: "M.Tech",
    email: "keerthi.v@gnits.ac.in",
    phone: "040-29565856 Extn. 416",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 9,
    name: "Mrs. SRAVANTHI VUKANTI",
    position: "Associate Professor",
    qualifications: "M.Tech",
    email: "sravanthi.v@gnits.ac.in",
    phone: "040-29565856 Extn. 419",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 10,
    name: "Mr. BANOTH SRINU",
    position: "Associate Professor",
    qualifications: "M.Tech",
    email: "srinu.b@gnits.ac.in",
    phone: "040-29565856 Extn. 427",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 11,
    name: "Mr. GADE VENKATA SUBBA REDDY",
    position: "Associate Professor",
    qualifications: "M.Tech",
    email: "subba.reddy@gnits.ac.in",
    phone: "040-29565856 Extn. 425",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 12,
    name: "Mr. RAMESH GUGULOTHU",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "ramesh.g@gnits.ac.in",
    phone: "040-29565856 Extn. 414",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 13,
    name: "Mr. GATTU SANDEEP",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "sandeep.g@gnits.ac.in",
    phone: "040-29565856 Extn. 412",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 14,
    name: "Mr. BALLEPU KUMAR NAVEEN",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "kumar.naveen@gnits.ac.in",
    phone: "040-29565856 Extn. 416",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 15,
    name: "Mr. ANIL MOGURAM",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "anil.m@gnits.ac.in",
    phone: "040-29565856 Extn. 419",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 16,
    name: "Mrs. VIJAYAGIRI LATHA SRI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "latha.sri@gnits.ac.in",
    phone: "040-29565856 Extn. 427",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 17,
    name: "Mrs. MARNENI SWAPNA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 18,
    name: "Mrs. BORRA SAI PRANEETHA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 19,
    name: "Mr. BHUSHABOINA SANTHOSH KUMAR",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 20,
    name: "Mrs. CHIDURALA KAVITHA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 21,
    name: "Mrs. AMBATI PRUTHARANI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 22,
    name: "Mrs. HEMALATHA MADDIGATLA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 23,
    name: "Mrs. MADDALA KIRANMAYI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 24,
    name: "Mrs. CH. SWAPNA",
    position: "Lab Assistant",
    qualifications: "B.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 25,
    name: "Ms. T. BHAGYA SRI",
    position: "Lab Assistant",
    qualifications: "B.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 26,
    name: "Ms. P. ANUSHA RANI",
    position: "Lab Assistant",
    qualifications: "B.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 27,
    name: "Ms. R. MANASA",
    position: "Lab Assistant",
    qualifications: "B.Tech",
    email: "",
    phone: "",
    academicIdentity: "/academic-identity-link",
  },
];

const csehod = {
  branch: "Computer Science and Engineering (CSE)",
  name: "Dr. Dinesh Kumar Rangarajan",
  position: "Professor & HOD",
  qualifications: "Ph.D",
  description:
    "Dr. Dinesh Kumar Rangarajan leads the CSE department with vast academic and research experience.",
  email: "dinesh.kumar@cse.institute.com",
  phone: "040-29565856 Extn. 500",
  academicIdentity: "/academic-identity-link",
  photo: "/images/chairman.jpg",
};

// Faculty Members Data
const cseprofessors = [
  {
    id: 1,
    name: "Dr. AKELLA SATYANARAYANA",
    position: "Professor",
    qualifications: "Ph.D",
    email: "akella.s@cse.institute.com",
    phone: "040-29565856 Extn. 501",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 2,
    name: "Dr. PULIME SATYANARAYANA",
    position: "Professor",
    qualifications: "Ph.D",
    email: "pulime.s@cse.institute.com",
    phone: "040-29565856 Extn. 502",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 3,
    name: "Dr. NITTALA SWAPNA SUHASINI",
    position: "Professor",
    qualifications: "Ph.D",
    email: "nittala.ss@cse.institute.com",
    phone: "040-29565856 Extn. 503",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 4,
    name: "Dr. KISHORE KUMAR KALEVAR",
    position: "Professor",
    qualifications: "Ph.D",
    email: "kishore.k@cse.institute.com",
    phone: "040-29565856 Extn. 504",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 5,
    name: "PRATHAP KUNCHALA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "prathap.k@cse.institute.com",
    phone: "040-29565856 Extn. 505",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 6,
    name: "DAMERA SAMMAIAH",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "damera.s@cse.institute.com",
    phone: "040-29565856 Extn. 506",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 7,
    name: "RADHIKA GOLI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "radhika.g@cse.institute.com",
    phone: "040-29565856 Extn. 507",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 8,
    name: "BASANABOINA RAJU",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "basanaboina.r@cse.institute.com",
    phone: "040-29565856 Extn. 508",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 9,
    name: "JYOTI CHILOKA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "jyoti.c@cse.institute.com",
    phone: "040-29565856 Extn. 509",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 10,
    name: "MANJULA LINGESWAR",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "manjula.l@cse.institute.com",
    phone: "040-29565856 Extn. 510",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 11,
    name: "BODDUPALLY SANDEEP KUMAR",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "sandeep.b@cse.institute.com",
    phone: "040-29565856 Extn. 511",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 12,
    name: "GANDRA BRAHMAM",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "gandra.b@cse.institute.com",
    phone: "040-29565856 Extn. 512",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 13,
    name: "SATISH VEMULA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "satish.v@cse.institute.com",
    phone: "040-29565856 Extn. 513",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 14,
    name: "CHIRANJEEVI KOMMULA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "chiranjeevi.k@cse.institute.com",
    phone: "040-29565856 Extn. 514",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 15,
    name: "CHAITAN SHILPA KOLISHETTI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "shilpa.k@cse.institute.com",
    phone: "040-29565856 Extn. 515",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 16,
    name: "TAGARAM ANUSHA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "anusha.t@cse.institute.com",
    phone: "040-29565856 Extn. 516",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 17,
    name: "KONDAPALLI SUNANDA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "sunanda.k@cse.institute.com",
    phone: "040-29565856 Extn. 517",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 18,
    name: "PENUGONDA SEETHA RAMA KRISHNA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "seetha.rk@cse.institute.com",
    phone: "040-29565856 Extn. 518",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 19,
    name: "B PRABHAKAR REDDY",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "prabhakar.r@cse.institute.com",
    phone: "040-29565856 Extn. 519",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 20,
    name: "GANJI SWATHI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "swathi.g@cse.institute.com",
    phone: "040-29565856 Extn. 520",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 21,
    name: "RAMYA YELAPATI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "ramya.y@cse.institute.com",
    phone: "040-29565856 Extn. 521",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 22,
    name: "KONDAPAKALA INDUMATHI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "indumathi.k@cse.institute.com",
    phone: "040-29565856 Extn. 522",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 23,
    name: "GUDIPURI RAMAKRISHNA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "ramakrishna.g@cse.institute.com",
    phone: "040-29565856 Extn. 523",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 24,
    name: "NALLA VIJAY KUMAR",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "vijaykumar.n@cse.institute.com",
    phone: "040-29565856 Extn. 524",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 25,
    name: "VIJAYAKUMAR NALAMOTHU",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "vijay.n@cse.institute.com",
    phone: "040-29565856 Extn. 525",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 26,
    name: "BARLA DIVYA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "divya.b@cse.institute.com",
    phone: "040-29565856 Extn. 526",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 27,
    name: "BALAJI GUGULOTH",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "balaji.g@cse.institute.com",
    phone: "040-29565856 Extn. 527",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 28,
    name: "VEMURI NAGA SRI MANASWINI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "manaswini.v@cse.institute.com",
    phone: "040-29565856 Extn. 528",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 29,
    name: "BEDAM NIKHITHA",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "nikhitha.b@cse.institute.com",
    phone: "040-29565856 Extn. 529",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 30,
    name: "ANGIDI VINAY KUMAR",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "vinay.a@cse.institute.com",
    phone: "040-29565856 Extn. 530",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 31,
    name: "PENTAPURI RAMYASREE",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "ramyasree.p@cse.institute.com",
    phone: "040-29565856 Extn. 531",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 32,
    name: "NOMULA MADHAVI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "madhavi.n@cse.institute.com",
    phone: "040-29565856 Extn. 532",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 33,
    name: "SANTHOSH REDDY AKETI",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "santhosh.a@cse.institute.com",
    phone: "040-29565856 Extn. 533",
    academicIdentity: "/academic-identity-link",
  },
  {
    id: 34,
    name: "GINNARAPU MAHINDER",
    position: "Assistant Professor",
    qualifications: "M.Tech",
    email: "mahinder.g@cse.institute.com",
    phone: "040-29565856 Extn. 534",
    academicIdentity: "/academic-identity-link",
  },
];

var ecepara =
  "The ECE faculty at GNITS are pioneers in the field, bringing vastindustry and research experience to the classroom. They are committed to mentoring students in emerging areas like AI, data science, and software engineering, ensuring they are well-prepared to lead in the tech industry.";
var csepara =
  "The CSE faculty at GNITS are pioneers in the field, bringing vastindustry and research experience to the classroom. They are committed to mentoring students in emerging areas like AI, data science, and software engineering, ensuring they are well-prepared to lead in the tech industry.";

export { ecehod, eceprofessors, ecepara, csehod, cseprofessors, csepara };
